#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: niccheva <niccheva@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/21 10:42:19 by niccheva          #+#    #+#              #
#    Updated: 2015/06/25 11:10:24 by niccheva         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

RESULT = atom

SOURCES =	atom.ml			\
			aluminium.ml	\
			carbon.ml		\
			helium.ml		\
			hydrogen.ml		\
			lithium.ml		\
			magnesium.ml	\
			nitrogen.ml		\
			oxygen.ml		\
			sodium.ml		\
			main.ml

include OCamlMakefile

fclean: cleanup
	rm -f $(RESULT)
